from app.models.enums import TransactionType

DEFAULT_CATEGORIES: tuple[dict[str, TransactionType | str | int], ...] = (
    {"name": "Salario", "type": TransactionType.INCOME, "sort_order": 10},
    {"name": "Freelance", "type": TransactionType.INCOME, "sort_order": 20},
    {"name": "Trabajos diarios", "type": TransactionType.INCOME, "sort_order": 30},
    {"name": "Ventas", "type": TransactionType.INCOME, "sort_order": 40},
    {"name": "Bonos", "type": TransactionType.INCOME, "sort_order": 50},
    {"name": "Inversiones", "type": TransactionType.INCOME, "sort_order": 60},
    {"name": "Regalos", "type": TransactionType.INCOME, "sort_order": 70},
    {"name": "Reembolsos", "type": TransactionType.INCOME, "sort_order": 80},
    {"name": "Otros ingresos", "type": TransactionType.INCOME, "sort_order": 90},
    {"name": "Alimentacion", "type": TransactionType.EXPENSE, "sort_order": 100},
    {"name": "Transporte", "type": TransactionType.EXPENSE, "sort_order": 110},
    {"name": "Vivienda", "type": TransactionType.EXPENSE, "sort_order": 120},
    {"name": "Luz", "type": TransactionType.EXPENSE, "sort_order": 130},
    {"name": "Agua", "type": TransactionType.EXPENSE, "sort_order": 140},
    {"name": "Internet", "type": TransactionType.EXPENSE, "sort_order": 150},
    {"name": "Servicios", "type": TransactionType.EXPENSE, "sort_order": 160},
    {"name": "Salud", "type": TransactionType.EXPENSE, "sort_order": 170},
    {"name": "Educacion", "type": TransactionType.EXPENSE, "sort_order": 180},
    {"name": "Suscripciones", "type": TransactionType.EXPENSE, "sort_order": 190},
    {"name": "Entretenimiento", "type": TransactionType.EXPENSE, "sort_order": 200},
    {"name": "Juegos", "type": TransactionType.EXPENSE, "sort_order": 210},
    {"name": "Salidas", "type": TransactionType.EXPENSE, "sort_order": 220},
    {"name": "Compras", "type": TransactionType.EXPENSE, "sort_order": 230},
    {"name": "Emergencias", "type": TransactionType.EXPENSE, "sort_order": 240},
    {"name": "Otros gastos", "type": TransactionType.EXPENSE, "sort_order": 250},
)
